### ISSUE TITLE
Suddenly can't use it

### ISSUE THREAD

**Issue by Remtobbb** [BlueAmulet/GreenLuma-2024-Manager#73]
error.log appears after running manager
the content is as follows

INFO:root:GreenLuma 2023 Manager 1.3.9
INFO:root:Launched DLLInjector.exe, exiting

**Comment by BlueAmulet** [comment]
Going to need to be more descriptive as to what "can't use it" means.
Is there an issue in the Manager or with GreenLuma? Are you keeping your GreenLuma up to date? Does Steam launch at all after hitting "Run GreenLuma", or is it just that things do not unlock?

**Comment by Remtobbb** [comment]
> Going to need to be more descriptive as to what "can't use it" means. Is there an issue in the Manager or with GreenLuma? Are you keeping your GreenLuma up to date? Does Steam launch at all after hitting "Run GreenLuma", or is it just that things do not unlock?

Steam can be restarted, but games cannot be unlocked.

**Comment by Remtobbb** [comment]
> Going to need to be more descriptive as to what "can't use it" means. Is there an issue in the Manager or with GreenLuma? Are you keeping your GreenLuma up to date? Does Steam launch at all after hitting "Run GreenLuma", or is it just that things do not unlock?

Steam can be restarted, but games cannot be unlocked.
I just tried only using greenluma and it didn't work either. It seems I need to ask on the greenluma forum.
