### ISSUE TITLE
GreenLuma_2020_x86.dll

### ISSUE THREAD

**Issue by yingwai** [BlueAmulet/GreenLuma-2024-Manager#75]
GL 1.5.4 uses GreenLuma_2024_x86.dll, and it is in the folder, the path in GLM is correct, but it does not use file 24, but looks for 20, which no longer exists
![image](https://github.com/BlueAmulet/GreenLuma-2024-Manager/assets/56441118/351f9c85-2c32-44b0-921f-bdc8a6c81758)
![image](https://github.com/BlueAmulet/GreenLuma-2024-Manager/assets/56441118/f22a60d2-1952-4117-bea1-35b47534bafd)

although the truth is that sometimes it launches the application correctly, but sometimes it asks for an unnecessary file. I haven’t figured out any pattern yet(

**Comment by BlueAmulet** [comment]
The DLL it uses is based on what is listed in the DLLInjector.ini. Please update the Dll parameter to point to the correct dll.

**Comment by yingwai** [comment]
Hm, if an error appears, I’ll definitely look in the parameters, thanks for the help

**Comment by BlueAmulet** [comment]
Wrong Dll listed in .ini should now be handled better as of v1.3.10
