### ISSUE TITLE
Stopped working randomly last 2 weeks

### ISSUE THREAD

**Issue by kratos1912** [BlueAmulet/GreenLuma-2024-Manager#77]
I've been using it since start of the year and no problem. Now it stopped working, old version nor latest one. I can't bypass family share limitations anymore. The games still appears to be from friend library and not mine

**Comment by DarkArtistryGH** [comment]
GreenLuma stops working in the new version of Steam Family Sharing

**Comment by BlueAmulet** [comment]
Not noticing any issues with GreenLuma, either way not an issue with the manager.
