### ISSUE TITLE
DllInjector.exe missing

### ISSUE THREAD

**Issue by LunarRuby** [BlueAmulet/GreenLuma-2024-Manager#81]
Its straight up just not there within my install directory, windows didnt eat it because I checked it, and I even turned it off afterwards.
![image](https://github.com/user-attachments/assets/6b65d5f3-6ac2-40e6-9ac7-9bd61f50ab92)

**Comment by BlueAmulet** [comment]
Not an issue with the manager. Obviously something did eat it, go make sure whatever antivirus you're using has it excluded and reextract GreenLuma.
